backend:
  name: github
  repo: Choxie77/PhoThai-Massage
  branch: main
  base_url: https://decap-cms-oauth2.netlify.app

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "services"
    label: "Services"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Service Name", name: "title", widget: "string"}
      - {label: "60min Price (THB)", name: "price_60", widget: "number"}
      - {label: "90min Price (THB)", name: "price_90", widget: "number"}
